### PR TITLE
Bump version to 0.0.3

### PR DESCRIPTION
**Pull request by RusinovAnton**

### CODE REVIEW

**Comment by AnastasiiaLisovska** [comment]
LGTM

**Comment by RusinovAnton** [comment]
I guess now its not uploading because of our migration to npm's private modules
https://github.com/yola/production/issues/2231#issuecomment-344119913.

https://jenkins.yola.net/job/Upload-eslint-plugin-yola/4/console
```
npm ERR! 404 User not found : eslint-plugin-yola
npm ERR! 404 
npm ERR! 404  'eslint-plugin-yola' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by RusinovAnton** [comment]
@stefanor what can be done with uploading build in this case?

**Comment by stefanor** [comment]
Fixed in yola/chef#2170

**Pull request merged**
